### ISSUE TITLE
[Question] Where the todos are stored

### ISSUE THREAD

**Issue by kanlukasz** [souravlayek/VS-Todo-Extension#1]
Hello,
Interesting extension.

Can you tell me where the todos are stored?
Can they be stored in a specific file in my project folder?

**Comment by souravlayek** [comment]
They are storing in the workspace states created by vscode itself.
No, not now, I am thinking in the next update using a file for more flexibility.
If you want and can please implement that feature it is completely open source.

**Comment by souravlayek** [comment]
I am closing the issue as it is not any bug report.
