### ISSUE TITLE
Suggestion: choose todo storage

### ISSUE THREAD

**Issue by ricardo-coverwallet** [souravlayek/VS-Todo-Extension#2]
Hi,

sometimes I had to remove the folder of a project because I did a whole mess, so I needed to clone again from the server. The issue is that all my todo items disappeared. It would be awesome to be able to configure where to store those items so I can select an external folder and make sure I'm not going to lose anything.

Thanks

**Comment by souravlayek** [comment]
Sorry man appreciate you thought, I am thinking connecting it with some kind of server, thanks for your concern. I would love to marge you PR if you wanna contribute
